SUBJECT_CODES = [
    ('AE', 'Aerospace Engineering'),
    ('ARCH', 'Architecture'),
    ('BIOL', 'Biology'),
    ('BMED', 'Biomedical Engineering'),
    ('BC', 'Building Construction'),
    ('CHBE', 'Chemical and Biomolecular Engineering'),
    ('CHEM', 'Chemistry'),
    ('CEE', 'Civil Engineering'),
    ('ECE', 'Computer Engineering'),
    ('CS', 'Computer Science'),
    ('EAS', 'Earth and Atmospheric Sciences'),
    ('ECON', 'Economics'),
    ('EE', 'Electrical Engineering'),
    ('HTS', 'History, Technology, and Society'),
    ('ID', 'Industrial Design'),
    ('ISYE', 'Industrial Engineering'),
    ('INTA', 'International Affairs'),
    ('LMC', 'Literature, Media, and Communication'),
    ('MSE', 'Materials Science and Engineering'),
    ('MATH', 'Mathematics'),
    ('ME', 'Mechanical Engineering'),
    ('NEUR', 'Neuroscience'),
    ('NRE', 'Nuclear and Radiological Engineering'),
    ('PHYS', 'Physics'),
    ('PYSC', 'Psychology'),
    ('PUBP', 'Public Policy'),
    ('CSE', 'Computational Science and Engineering'),
    ('GMC', 'Global Media and Cultures'),
    ('HCI', 'Human-Computer Interaction'),
    ('IL', 'International Logistics'),
    ('MP', 'Medical Physics'),
    ('MGT', 'Management'),
    ('HS', 'Health Systems')
]